version:
    plugin:
    schema:
log:
    pvp-death: true
    mob-death: true
    other-death: true
    command: true
    chat: true
    join: true
    quit: true
    teleport: true
    door-interact: true
    open-container: true
    container-transaction: true
    item-pickup: true
    item-drop: true
    button: true
    lever: true
    explosion: true
    flint-steel: true
    lava-bucket: true
    water-bucket: true
    water-flow: false
    lava-flow: false
    sign-place: true
    sign-break: true
    painting-place: true
    painting-break: true
    block-place: true
    block-break: true
    block-burn: true
    block-fade: true
    block-form: true
    tree-grow: true
    leaf-decay: true
    mushroom-grow: true
    enderman-pickup: true
    enderman-place: true
    other: true
general:
    max-lines: 0
    check-for-updates: false
    debug: false
    log-ip-addresses: true
    cleanse: false
    cleanse-period: 20m
    cleanse-age: '0'
    delete-data-on-rollback: false
    max-radius: 0
    tool-block: '17'
    default-tool-command: ''
    default-here-radius: 5
    log-item-drops-on-death: false
mysql:
    hostname: localhost
    port: 3306
    username: minecraft
    password: ''
    database: hawkeye
    max-connections: 10
    hawkeye-table: hawkeye
    player-table: hawk_players
    world-table: hawk_worlds
ignore-worlds:
- ignorethisworld
command-filter:
- /login
- /restartsrv
- /register
block-filter:
- 140
- 150
