name: ${project.plugin.name}
main: ${project.plugin.main}
author: ${project.plugin.author}
version: ${project.plugin.version}
description: ${project.plugin.description}
softdepend: ${project.plugin.depend}
commands:
  hawk:
    description: ${project.plugin.description}
    aliases: [hawkeye,he,hk,ha]
    usage: /<command> help
permissions:
    hawkeye.*:
        description: Gives access to all HawkEye commands
        children:
            hawkeye.search: true
            hawkeye.tpto: true
            hawkeye.rollback: true
            hawkeye.tool: true
            hawkeye.notify: true
            hawkeye.preview: true
    hawkeye.tool.*:
        description: Permission to use the HawkEye tool
        children:
            hawkeye.tool.bind: true
